---
- name: Display current date and time in IST and one hour ahead time
  hosts: localhost
  tasks:
    - name: Get current time and date
      command: date +%Y-%m-%dT%T%z
    - name: Display current time and date
      debug:
        msg: The current date and time in IST is {{ lookup('pipe', 'date +%Y-%m-%dT%T%z') }}
    - name: Get one hour ahead time
      command: date --date='1 hour' +%Y-%m-%dT%T%z
    - name: Display one hour ahead time
      debug:
        msg: One hour ahead time in IST is {{ lookup('pipe', 'date --date=''1 hour''+%Y-%m-%dT%T%z') }}
